Repository milieuinfo/webcomponent-vl-ui-input-field, pull requests merged in 2019-09, with the labels that each got.

#19 UIG-218
  vl-input-field.src.js
Labels: maintenance

#20 Update link naar demo
  vl-input-field.src.js
Labels: maintenance

#22 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#25 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#24 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#23 Update dependency @govflanders/vl-ui-input-field to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#10 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#26 Revert naar @govflanders 3.7.2
  package-lock.json
  package.json
Labels: bug

#28 Automatic commit via update script
  demo/demo.css
  package-lock.json
  style.css
Labels: maintenance

#32 UIG-143 - Update bamboo template
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance

#33 Update vl-ui-util
  CODEOWNERS
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance
