Repository milieuinfo/webcomponent-vl-ui-input-field, pull requests merged in 2019-10, with the labels that each got.

#34 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance

#39 #37 Validatie functionaliteit toevoegen via vl-ui-form-validation
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: enhancement

#36 Update README.md
  README.md
Labels: maintenance

#42 #41 Formulier validatie type classes automatisch toevoegen
  README.md
  test/vl-input-field.test.html
  vl-input-field.src.js
Labels: chore

#40 update README.md
  README.md
Labels: maintenance

#44 Update README.md
  README.md
  package.json
Labels: maintenance
